### ISSUE TITLE
[ADD] image upload & fetch 

### ISSUE THREAD

**Issue by KimDaeSeong8721** [DeveloperAcademy-POSTECH/toGather#107]
## 💡 Issue

- 이미지 upload & fetch 구현 
-  상세정보뷰의 인증사진 연결
## 📝  todo
- [x] ThisWeek에 imageUrl 저장
- [x] firebase storage에 이미지파일 저장
- [x] ThisWeek 모아둔 weekInfo로부터 imageUrl들 취합하여 상세정보사진에 연결
- [x]  Kingfisher이용
