### ISSUE TITLE
[Fix] UI 디테일 수정 사항들

### ISSUE THREAD

**Issue by yudonlee** [DeveloperAcademy-POSTECH/toGather#112]
## 💡 Issue

[온보딩/친구추가 저축 페이지] 핀번호 텍스트 필드 안에 글자 볼드체로 수정
[온보딩/마지막 확인페이지] "저축내용을 수정할게요"시 첫화면으로 이동, 저축버튼 위치수정

## 📝  todo
- [ ] [온보딩/친구추가 저축 페이지] 핀번호 텍스트 필드 안에 글자 볼드체로 수정
- [ ] [온보딩/마지막 확인페이지] "저축내용을 수정할게요"시 첫화면으로 이동
- [ ] [온보딩/마지막 확인페이지] "저축버튼 위치수정"
