### ISSUE TITLE
[FEAT] 메인 뷰 만들기

### ISSUE THREAD

**Issue by KimDaeSeong8721** [DeveloperAcademy-POSTECH/toGather#12]
## 💡 Issue

<img width="252" alt="스크린샷 2022-06-09 오후 3 45 39" src="https://user-images.githubusercontent.com/69894461/172782255-d90bff5a-ba5e-4778-9601-0a955458147b.png">

- 메인 뷰 만들기
## 📝  todo

- [x] 친구 저축현황 서브뷰 만들기
- [x] 나의 저축현황 서브뷰 만들기
- [x] 바텀 버튼뷰 만들기
