### ISSUE TITLE
[FEAT] 

### ISSUE THREAD

**Issue by limhyoseok** [DeveloperAcademy-POSTECH/toGather#121]
## 💡 Issue

메인뷰에서 친구를 추가할 경우 온보딩에 있는 친구 추가 뷰로 연결이 된다. 
따라서 친구 추가를 하면 다음 온보딩 페이지로 넘어가는 문제가 발생함

위의 문제를 해결하는 방법 중 하나는
**메인에서 친구 추가를 위한 "FriendAddtionView"를 별도로 만들면 된다.**

하지만 현재 친구 추가 뷰는 온보딩만을 위한 뷰이기 때문에 재활용을 하기 위해서 온보딩과 관련된 부분을 제거해야한다.

## 📝  todo
- [ ] [FIX] 기존 FriedsAdditionView에서 다음 버튼 제거하기
- [ ] [FEAT] 친구 추가 for onboarding view 생성
- [ ] [FEAT] 친구 추가 for MainView 생성
