### ISSUE TITLE
[FEAT] 온보딩 마지막 페이지 만들기

### ISSUE THREAD

**Issue by unuhqueen** [DeveloperAcademy-POSTECH/toGather#14]
## 💡 Issue

<img width="208" alt="스크린샷 2022-06-09 오후 7 48 48" src="https://user-images.githubusercontent.com/49133245/172830298-fdf99092-2f62-4061-a945-cfc919886359.png">

- 온보딩 마지막 페이지 만들기

## 📝  todo
- [x] 뷰 그리기
- [ ] 뷰모델 이용해서 데이터 업로드하기
- [ ] 뒤로 돌아가는 버튼 구현하기
- [ ] 다음 화면으로 넘어가는 버튼 구헌하기
