### ISSUE TITLE
[FEAT] Saving image 불러오고 날짜 표시 

### ISSUE THREAD

**Issue by yudonlee** [DeveloperAcademy-POSTECH/toGather#143]
## 💡 Issue

<img width="208" alt="image" src="https://user-images.githubusercontent.com/39371835/184051923-15431bbe-7d73-4b7d-b224-ef65e88bec10.png">

## 📝  todo
- [ ] 서버에서 사진 불러오기
- [ ] 불러온 사진에 날짜 데이터 처리
- [ ] 날짜 데이터를 며칠전으로 볼 수 있도록 로직 처리
