### ISSUE TITLE
[FEAT] 친구추가 뷰 만들기 

### ISSUE THREAD

**Issue by yudonlee** [DeveloperAcademy-POSTECH/toGather#2]
## 💡 Issue

__친구추가 뷰__
<img src="https://user-images.githubusercontent.com/39371835/172538589-74caf85e-9261-4c13-aebe-fc8c85df4c3a.png" width="214.5" height="440.1">
## 📝  todo
- [ ] todo !

 - [x] 제목 및 부제목 View
 - [x] 친구 ID PIN번호 요청 View
 - [x] 잘못된 핀번호 입력시 햅틱반응 및 Shake Animation
 - [x] 추가 된 친구 프로필 Circle로 표시하기 및 원 우측 상단에 Remove Badge 넣기
