### ISSUE TITLE
[FEAT] 기간설정 뷰 만들기

### ISSUE THREAD

**Issue by limhyoseok** [DeveloperAcademy-POSTECH/toGather#3]
## 💡 Issue

<img src="https://user-images.githubusercontent.com/59302419/172543467-3593dc3b-f224-41a2-ab3b-03808c6f4b01.png" width="200" height="400"/>

## 📝  todo
- [x] view 구성하기 
- [ ] 슬라이더 이동시 변화하는 숫자로 다른 컴포넌트에 영향을 주지 않도록 변경
- [ ] 슬라이더 이동시 햅틱 구현
- [x] 간격 세세하게 조정
- [ ] 색깔 세세하게 조정
- [ ] 슬라이더 위에 따라다니는 글자 뛰우기
