### ISSUE TITLE
[FEAT] 목표설정 뷰 만들기

### ISSUE THREAD

**Issue by yeongwooCho** [DeveloperAcademy-POSTECH/toGather#6]
## 💡 Issue
<img width="308" alt="스크린샷 2022-06-09 09 59 21" src="https://user-images.githubusercontent.com/48707024/172742033-e7f13ab7-fa3b-4e2c-857e-04d2bbb9ed9f.png">

## 📝  todo
- [x] HStack으로 가로 아이템 나열
- [x] VStack으로 HStack 세로 나열
- [x] NavigationView setting
- [x] button 활성화/비활성화
- [x] 하나의 아이템만 선택 가능
