### ISSUE TITLE
[FEAT] 메인뷰 네비게이션 연결하기

### ISSUE THREAD

**Issue by limhyoseok** [DeveloperAcademy-POSTECH/toGather#78]
## 💡 Issue

<img width="686" alt="image" src="https://user-images.githubusercontent.com/59302419/174191945-dc1071a7-771c-4c7d-914a-82ea28b8f26f.png">

## 📝  todo
- [x] 메인뷰(나의 상세보기) -> 저축 상세 화면
- [ ] 메인뷰(저축기록) -> 저축 기록 화면
- [x] 메인뷰(친구 상세보기) -> 저축 상세화면
- [ ] 메인뷰(알림) -> 알림 화면
- [ ] 메인뷰(친구추가) -> 친구추가 화면
