### ISSUE TITLE
[FEAT] SavingStatusView 값 받아오기

### ISSUE THREAD

**Issue by yudonlee** [DeveloperAcademy-POSTECH/toGather#96]
## 💡 Issue

SavingStatusView에서 메인뷰에서 값을 받아와서 렌더링
## 📝  todo
- [ ] SavingStatusView에서 이미지 띄우기
- [ ] 사진편집 버튼 눌렀을때 삭제 뱃지 Active하기
- [ ] 사진 받아와서 Grid에 넣기
